version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: postgresql
    restart: always
    ports: 
      - "5432:5432"
    env_file: .env
    volumes: 
      - postgres:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    environment:
      NODE_ENV: production
    depends_on:
      - postgres
    env_file: .env

volumes:
  postgres: